const consts = {
    APP_DARK_COLOR: "#2a3042",
    APP_TITLE: "CHALET",
    CHANGE_CALENDAR: "Change Calendar",
    SCHEDULING_ASSISTANT: "Scheduling Assistant",
    CHANGE_INVENTORY: "Change Inventory",
    TEAM_CAPACITY: "Team Capacity",
    DL_NAME: "DL HXM-AppOps-Change Orchestration-Delivery",
    DL: "DL_62DAAACB3FE6DD029B030FF0@global.corp.sap",
    CREATION: "Creation",
    SCHEDULING: "Scheduling",
    EXECUTION: "Execution",
    VALIDATION: "Validation",
    REPORTING: "Reporting",
    CHANGE_CREATION_DESCRIPTION: "Utility to create changes on Service Now",
    CHANGE_SCHEDULING_DESCRIPTION: "Utility to schedule AppOps and Microservices changes",
    CHANGE_EXECUTION_DESCRIPTION: "Utility to execute changes manually or automatically.",
    CHANGE_VALIDATION_DESCRIPTION: "Utility to validate changes manually or automatically.",
    CHANGE_REPORTING_DESCRIPTION: "Statitics of the changes, capacity and effort.",
    API_URL: "https://change-tool-api.cfapps.us10.hana.ondemand.com",
    STANDARD_CHANGE: 'Standard Change',
    NORMAL_CHANGE: 'Normal Change',
    GET_USER_DATA: 'https://chalet.cfapps.us10.hana.ondemand.com/api/v1/user/currentUser',
    CREATE_STANDARD_CHANGE_JENKINS_LINK: 'https://jenkins.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/job/application-operations/job/SNOW-Ticket-Creation/job/Microservices-Standard-Change-Creation/',
    CHANGE_DATA: 'https://sap-my.sharepoint.com/:x:/p/mukta_sriram_gudlavalleti/EXaZ-A6XgPlGieMLs-S0DkIBoIFZWIFDPkYpZEawyhincg?e=L5cTg9',
    CREATE_STANDARD_CHANGE_DESCRIPTION: 'Utility to create Standard change on Service Now',
    CREATE_NORMAL_CHANGE_DESCRIPTION: 'Utility to create Normal change on Service Now',
    NOTIFICATION_BORDER_GREEN:"#5AA835",
    NOTIFICATION_BORDER_RED:"#F44336",
    NOTIFICATION_BORDER_YELLOW:"#F7C600",
    NOTIFICATION_BACKGROUND_RED:"#FFDDDD",
    NOTIFICATION_BACKGROUND_GREEN:"#EFF7EB",
    NOTIFICATION_BACKGROUND_YELLOW:"#FFF3CD",

}

export default consts;