const consts = {
  APP_DARK_COLOR: "#2a3042",
  APP_TITLE: "E-TRACKER",
  CREATE_EWAYBILL: "Create Ewaybill",
  DASHBOARD: "Dashboard",
  ARCHIVED: "Archived",
  COMPLETED: "Completed",
  HISTORY: "History",
  NOTIFICATION_BORDER_GREEN: "#5AA835",
  NOTIFICATION_BORDER_RED: "#F44336",
  NOTIFICATION_BORDER_YELLOW: "#F7C600",
  NOTIFICATION_BACKGROUND_RED: "#F44336",
  NOTIFICATION_BACKGROUND_GREEN: "#479D2D",
  NOTIFICATION_BACKGROUND_YELLOW: "#FFF3CD",
};

export default consts;
